{{- $shards := .Values.shardCount | int }}
apiVersion: v1
data:
  JINA_LOG_LEVEL: INFO
  pythonunbuffered: '1'
  worker_class: uvicorn.workers.UvicornH11Worker
kind: ConfigMap
metadata:
  name: indexer-head-configmap
  namespace: {{ template "pqlite-helm.namespace" . }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: indexer-head
  name: indexer-head
  namespace: {{ template "pqlite-helm.namespace" . }}
spec:
  ports:
  - name: port-expose
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-in
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: indexer-head
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-head
  namespace: {{ template "pqlite-helm.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer-head
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: indexer-head
        jina_deployment_name: indexer
        ns: {{ template "pqlite-helm.namespace" . }}
        pod_type: HEAD
        shard_id: ''
    spec:
      containers:
      - args:
        - executor
        - --name
        - indexer/head
        - --k8s-namespace
        - {{ template "pqlite-helm.namespace" . }}
        - --polling
        - '{"/index": "ANY", "/search": "ALL", "*": "ANY"}'
        - --port-in
        - '8081'
        - --runtime-cls
        - HeadRuntime
        - --pod-role
        - HEAD
        - --shards
        - {{ $shards | squote }}
{{- if gt $shards 1 }}
        - --uses-after-address
        - 127.0.0.1:8083
{{- end }}
        - --uses-metas
        - '{}'
        - --native
        command:
        - jina
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: JINA_DEPLOYMENT_NAME
          value: indexer
        envFrom:
        - configMapRef:
            name: indexer-head-configmap
        image: jinaai/jina:master-py38-perf
        imagePullPolicy: Always
        name: executor
        ports:
        - containerPort: 8080
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8081
{{- if gt $shards 1 }}
      - args:
        - executor
        - --name
        - indexer/uses-after
        - --k8s-namespace
        - {{ template "pqlite-helm.namespace" . }}
        - --uses
        - config.yml
        - --port-in
        - '8083'
        - --shards
        - {{ $shards | squote }}
        - --uses-metas
        - '{}'
        - --uses-with
        - '{"metric": {{ $.Values.metric }}}'
        - --native
        command:
        - jina
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: JINA_DEPLOYMENT_NAME
          value: indexer
        envFrom:
        - configMapRef:
            name: indexer-head-configmap
        image: numb3r3/pqlite-merger:latest
        imagePullPolicy: Always
        name: uses-after
        ports:
        - containerPort: 8083
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8083
{{- end }}
